### ISSUE TITLE
[Improvement] Filter courses in top menu dropdown "My Courses"

### ISSUE THREAD

**Issue by theopen-institute** [dbnschools/moodle-theme_fordson#115]
Thank you for this amazing theme. My organization does distance education in rural Nepal, and Fordson has improved our work significantly. Many of our students are new to the internet, and we've struggled to find another theme with sufficient clarity.

To keep things simple, we've turned off the side navbar and use the "My Courses" menu dropdown to navigate. Across many sessions, however, the list is getting unmanageably long for our instructors. Is there a way to filter the courses listed here to show only those currently in progress (as per dates in the course settings)? Looking at the code, I didn't see anything obvious, but I thought perhaps there might be an indirect way that people have used.

I'm happy to contribute a pull request if able, but I thought I'd post an issue first to get some guidance on the best way to proceed.

-Peter

**Comment by hasqld** [comment]
Hi Peter.

I'm another Fordson Theme end user with a secondary school full of teachers who are big fans of what Fordson does for Moodle UI.

We use Moodle for lots of content management outside of standard student teaching needs and have a possibly similar situation to yours in that teachers, especially, are enrolled in lots of courses. As a result we've turned off the Fordson provided My Courses menu and have written a local plugin to provide up to four drop-down bootstrap menus instead which are populated with logic based around course categories and roles. It does this semi-dubiously via overwriting the $CFG->custommenuitems variable managed under "appearance" -> "theme settings" but it works very well for our needs. It also does a few other random UI and functionality tweaks we've hacked together over the years to make Moodle work better for us as an Intranet service solution.

I've copied the code onto github at https://github.com/hasqld/moodle_hillbrook_custom_ui in case it's of any use to you.

**Comment by theopen-institute** [comment]
Oliver / @hasqld,

Thank you so much! This is extremely helpful, and at first glance it appears to be perfect for our uses with only minor modification. Your sharing is greatly appreciated.

-Peter

**Comment by dbnschools** [comment]
When creating Fordson we initially designed it and wanted to eliminate the left sidebar. It proved troublesome to eliminate it outright and we backed off but left the code in there in case others liked it.  

What we've found is that even with all the navigational changes and Moodle UI improvements, struggles persisted with users.  There is just too many places to look for links on where or what you want to do.  Switch Role is buried in User Menu.  Custom Dashboard won't display links for third party plugins that get injected into the Course Admin area.  The left sidebar, the right sidebar, turn editing on, blocks, etc. etc.  Drop down menus that arbitrarily highlight certain pages of the course admin before taking you to the full page of menus.  Multiple ways to get to areas depending on what context or what drop down menu.  These elements all make a complex system more complex.

With all that in mind, we started a new project meant to simplify the UI beyond what Fordson does.  It's meant to make hidden elements obvious.  https://moodle.org/plugins/theme_rebel and https://github.com/dbnschools/moodle-theme_rebel
The new theme is MUCH simpler if you wanted to improve it or make changes for your organization.  We kept many of the things that made Fordson a great theme but eliminated non-essential stuff to keep things as easy as possible.  Instead of color choosers we display a full list of SCSS Variables used in the theme so you can customize many aspects of the theme quite simply by setting the variable color such as $breadcrumblinkcolor: $white;
