### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by soodkritika** [dbnschools/moodle-theme_fordson#17]
When I use mobile device, the theme is not responsive: the navigation bar overlapped the main content.
Would you be able to have a look ?

**Comment by dbnschools** [comment]
What version of Fordson and Moodle and what part of the navigation exactly?

**Comment by soodkritika** [comment]
fordson version: 2018020200(v1.7)
moodle version:  Moodle 3.4

Full nav drawer on the left side of page.

**Comment by dbnschools** [comment]
Do you have a screenshot?

**Comment by soodkritika** [comment]
![2018-04-27-15-37-12](https://user-images.githubusercontent.com/26106451/39426387-358e2b24-4c9d-11e8-9227-0603154f8d07.png)

**Comment by soodkritika** [comment]
@dbnschools  above is the screenshot where the navigation bar is overlapping the main content on dashboard.

**Comment by dbnschools** [comment]
That is how Core Moodle displays the navigation.  You use the scroll to move down.  You click the button to hide it once you are done using the navigation drawer.  

This is exactly how Boost displays the very same menu.

**Comment by soodkritika** [comment]
But I want some custom css that will adjust the expanded navigation bar on small screen.

**Comment by dbnschools** [comment]
OK.  Then use your custom css, but this doesn't mean Fordson is not responsive.  If you want to develop beyond what is offered then you can do so.  This is not an issue with Fordson but an issue with whatever custom CSS you are trying to use.  Please ask for help in the Moodle.org theme forum as a new post to help you expand functionality of the Boost Nav Drawer.  
I am closing this because it is not an issue or error in the theme.
