### ISSUE TITLE
Fordson Child-Theme?

### ISSUE THREAD

**Issue by antibrick** [dbnschools/moodle-theme_fordson#42]
Is it possible to create a child template of Fordson?
When we try, we always encounter "Exception - Call to undefined method core_renderer::region_main_settings_menu()" "line 57 of /theme/fordson/layout/frontpage.php: Error thrown"…
I'd really like it! We need to make a bunch of customisations.

**Comment by dbnschools** [comment]
Not quite sure how you would do that.  I can tell you Fordson is a child theme of Boost.  So that might play into the error you are getting.  How are you going about making a child theme?  What is your file structure?  There are several files that must be there.  I've never made a child theme to a child theme.  Ask Richard Oelmann or Gareth Barnard at Moodle.org as they might offer some insights on this.  https://moodle.org/mod/forum/view.php?id=46

**Comment by antibrick** [comment]
Hmm… I've already tried out a lot, following this tutorial: https://docs.moodle.org/dev/Creating_a_theme_based_on_boost
Child theme of child theme shouldn't be a problem…
I'll keep trying.

**Comment by dbnschools** [comment]
I wonder what the error would be with this:
 $regionmainsettingsmenu = $OUTPUT->region_main_settings_menu();

Richard Oelmann was originally who helped me get started with creating a child theme.  Boost was a bit different and the docs might not be complete.

**Comment by antibrick** [comment]
I just commented out the $regionmainsettingsmenu = $OUTPUT->region_main_settings_menu(); line… Now I can install the theme, it just looks strange and shows a bunch of notices…
I will try to contact Mr Oelmann, too… Thanks.
