### ISSUE TITLE
Course Completion missing from Student Course Dashboard

### ISSUE THREAD

**Issue by Robynstar** [dbnschools/moodle-theme_fordson#67]
Our clients have Course Completion and Show Student Completion enabled yet the Course Completion radial is no longer displaying in the Student Course Dashboard. Only the My Grades icon is present in that row.

If this functionality has been moved to the student's regular dashboard (which I see now shows percent completion on all the courses) the Fordson settings needs some cleaning up to prevent confusion as the course completion radial is also mentioned in the help text for theme_fordson|coursemanagementtoggle. However seeing as the specific setting theme_fordson|showstudentcompletion is still present I'm guessing this is just a minor bug? I'm hoping so as our clients would quite like it back on the Student Course Dashboard!

Our clients have noticed this since we moved to the 3.6 version of the theme and it is still present in the 2019111001 release.

**Comment by dbnschools** [comment]
If you upgraded to Moodle 3.6 you will notice that Moodle removed all css and supporting radial display from the Boost theme.  Thus, Fordson lost this too.  I was hoping to bring it back but have been put on another project here at work.  When moving to Moodle 3.6 we recommend using the Dashboard instead of site home as the default page.  This allows the student to manipulate the course ordering and view course completion status.  Most likely I am going to remove the radial but will try to work in the new bar style completion.

**Comment by dbnschools** [comment]
I'm working on an update and I included the new progress bar back into the student dashboard.  It's different but will be more inline with the rest of Moodle.

**Comment by dbnschools** [comment]
![student dashboard2](https://user-images.githubusercontent.com/28066305/53567687-003c5880-3b2e-11e9-84cf-3c2c4df23e15.png)

**Comment by Kordopatis** [comment]
Goodmorning from sunny Greece! Any possible way to have the code ? Thanks in advance.
