### ISSUE TITLE
Possible bug when using Fordson v3.7r1 with the Sharing Cart plugin

### ISSUE THREAD

**Issue by acquaalta** [dbnschools/moodle-theme_fordson#78]
Hi,

Moodle version: Moodle 3.7
Theme Version: Moodle 3.7 Fordson v3.7 release 1
Sharing Cart plugin version: 3.6, release 1

After I copy a section into the sharing cart, I can't paste it into the other course. When I click the "Copy to course" button in the block, the section just expands/collapses, as if I just clicked its name.

I know that the "Sharing Cart" plugin officialy doesn't support Moodle v3.7 yet, but please note that this bug doesn't happen when using the original Boost theme.

So I can still copy specific items to a course , but not an entire section.

Could you please check this issue? Maybe I'm missing something.

**Comment by dbnschools** [comment]
It's impossible for us to test against every plugin.  I will try to take a look but we are in the middle of major server and software updates during the summer.  I probably won't be able to take a look until August.  The sharing cart is not something we use.  We are placing bets on being able to use Moodle.NET for better sharing and curation by teachers in order to increase collaboration amongst staff.
