### ISSUE TITLE
Text fields can't be expanded horizontally

### ISSUE THREAD

**Issue by acquaalta** [dbnschools/moodle-theme_fordson#82]
Hi,
For some reason, when using the Fordson theme, I can't expand text fields to the sides (horizontally), only vertically.

Please see attached two animated GIFs - One shows the expected behavior in other themes (Adaptable, for example), and the other one shows the unexpected behavior in Fordson.

Thanks :-)

![Adaptable-Expanding-text-fields](https://user-images.githubusercontent.com/51836675/61355314-c5d51d00-a87c-11e9-93eb-fa454a92e740.gif)
![Fordson-Expanding-text-fields](https://user-images.githubusercontent.com/51836675/61355318-c66db380-a87c-11e9-9e39-494d9fea506e.gif)

**Comment by hasqld** [comment]
I'm just another Fordson user but I think this will be because the default style/css for Fordson has a setting of:

.editor_atto_content {
  resize: vertical;
}

So, assuming you are in fact using the default Atto editor, this is only allowing the text-area to be resized vertically.

If you add your own custom css settings you should be able to change it to the following and override that setting:

.editor_atto_content {
  resize: both;
}

I tested adding this under Site Administration -> Appearance -> Themes -> Fordson -> Colours
and it did the trick.

**Comment by acquaalta** [comment]
> I'm just another Fordson user but I think this will be because the default style/css for Fordson has a setting of:
> 
> .editor_atto_content {
> resize: vertical;
> }
> 
> So, assuming you are in fact using the default Atto editor, this is only allowing the text-area to be resized vertically.
> 
> If you add your own custom css settings you should be able to change it to the following and override that setting:
> 
> .editor_atto_content {
> resize: both;
> }
> 
> I tested adding this under Site Administration -> Appearance -> Themes -> Fordson -> Colours (in the Raw SCSS section) and it did the trick.

Thanks a lot :-)

**Comment by acquaalta** [comment]
For the record, the field in the example wasn't an Atto field, so I used the following code:

textarea .form-control {
resize: both;
}
