### ISSUE TITLE
Upgrade to Moodle 3.8 from v3.6 failed with fatal error when Fordson theme is applied 

### ISSUE THREAD

**Issue by swinster** [dbnschools/moodle-theme_fordson#98]
Upgrade seemed to progress fine. Login screen appeared, and after login was presented with:

Fatal error: Class 'theme_boost\output\core\files_renderer' not found in /opt/bitnami/apps/moodle/htdocs/theme/fordson/classes/output/core/files_renderer.php on line 38

**Comment by swinster** [comment]
Not sure if this is a fordson issue or not, however, rolling back to the pre upgrade state, then changing the theme to the default boost, then re-upgrading, all works fine.

The issue after login in when you are redirected to https://demomoodle.pexipacademy.com/admin/upgradesettings.php?

**Comment by Luzevn** [comment]
just comment next lines in  /theme/fordson/classes/output/core/files_renderer.php
it's a bug.
// class files_renderer extends \theme_boost\output\core\files_renderer {
    // Error message when this class is not included, but even if empty it works.
//}

**Comment by dbnschools** [comment]
Be sure to switch to the default theme during upgrades.  Between Moodle 3.5 and 3.8 there were many changes and many upgrades to core Moodle  and Boost.  Fordson in Moodle 3.5 will not operate in Moodle 3.7 due to many changes in core. Once the upgrade is done, be sure to get Fordson updated to the the Fordson release for that version of Moodle.

If you are on Moodle 3.5 you should not have the latest version which is for Moodle 3.9.  There will be compatibility issues.
